name: terminator
channels:
  - pytorch-nightly
  - nvidia
  - defaults
  - pyg
dependencies:
  - python=3.11
  - h5py
  - matplotlib
  - scikit-learn
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit
  - torchtext
  - plotly
  - pyg
  - pip
  - pip:
    - hydra-core==1.2.0
    - wandb==0.12.17
    - datasets==2.2.2
    - pytorch-lightning==1.6.4
    - torchmetrics==0.9.0
    - torch_optimizer
    - cupy-cuda11x
    - einops
    - spikingjelly
